version: '3.8'

services:
  selogertoken:
    build:
      dockerfile: seloger-token.Dockerfile
      context: .
    container_name: hobo-seloger-token
    restart: unless-stopped
    ports:
    - 8001:8001
    expose:
      - 8001

  moteurimmotoken:
    build:
      dockerfile: moteurimmo-token.Dockerfile
      context: .
    container_name: hobo-moteurimmo-token
    restart: unless-stopped
    ports:
      - 18081:18081
    expose:
      - 18081

  torproxy:
    build:
      context: torproxy
    container_name: torproxy
    restart: unless-stopped
    ports:
      - 9050:9050
      - 9052:9052
    expose:
      - 9050
      - 9052

  crawler:
    build:
      dockerfile: crawler.Dockerfile
      context: .
    container_name: hobo-sapiens-crawler
    restart: unless-stopped
    volumes:
      - ~/.hobo-sapiens/listings:/root/.hobo-sapiens/listings
      - ~/.hobo-sapiens/image-hashes:/root/.hobo-sapiens/image-hashes
      - ./filter.json:/usr/src/app/filter.json
        # Added by Hugo
      - ./flats.csv:/root/.hobo-sapiens/flats.csv
  depends_on:
      - selogertoken
      - moteurimmotoken
      - torproxy
    environment:
      - HS_FIRST_RUN_SILENT
      - HS_TELEGRAM_BOT_TOKEN
      - HS_TELEGRAM_CHAT_ID
      - TOR_PROXY_HOST=torproxy
      - HS_SELOGER_TOKEN_HOST=selogertoken
      - HS_MOTEURIMMO_TOKEN_HOST=moteurimmotoken
    expose:
      - 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #    - ~/.hobo-sapiens/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 0.0.0.0:13000:3000
    volumes:
  #    - ~/.hobo-sapiens/grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning/
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
